enableTelemetry: false

logFilters:
  - code: YN0062
    level: discard

nodeLinker: node-modules

packageExtensions:
  "@beyonk/google-fonts-webpack-plugin@*":
    dependencies:
      find-cache-dir: "^3.3.1"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-berry.cjs
