name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Increase available file watchers
        # https://stackoverflow.com/a/59522493/2560557
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc
          cache: "yarn"
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Tests
        run: yarn test --forceExit
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Test migration maker
        run: yarn make migration test
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox]
    steps:
      - name: Increase available file watchers
        # https://stackoverflow.com/a/59522493/2560557
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc
          cache: "yarn"
      - name: Install JavaScript Dependencies
        run: yarn install --immutable
      - name: Build for e2e tests
        run: yarn e2e-build
      - name: Install Roc & Roll Dependencies
        run: sudo apt update && sudo apt install ffmpeg
      - name: Install Playwright Dependencies
        # no need for `apt update` since that is already done above
        run: yarn playwright install-deps ${{ matrix.browser }}
      - name: Install Playwright Browser
        run: yarn playwright install ${{ matrix.browser }}
      - name: Run e2e tests
        run: yarn e2e-test:ci --project=${{ matrix.browser }}
  tooling-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc
          cache: "yarn"
      - name: Install Dependencies
        run: yarn install --immutable

      - name: "[client] compile"
        run: yarn tsc --build tsconfig.client.json --listFiles | tee client.files
      - name: "[server] compile"
        run: yarn tsc --build tsconfig.server.json --listFiles | tee server.files
      - name: "[all] compile"
        run: yarn tsc --build tsconfig.json

      - name: "[client] check forbidden imports"
        # The client should not import Express
        run: "! grep -E '@types/express' client.files"
      - name: "[server] check forbidden imports"
        # The server should not import React
        run: "! grep -E '@types/react'   server.files"
