name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - name: Increase available file watchers
      # https://stackoverflow.com/a/59522493/2560557
      run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install Dependencies
      run: yarn install --immutable
    - name: Tests
      run: yarn test --forceExit
    - name: Lint
      run: yarn lint
    - name: Build
      run: yarn build
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
    steps:
    - name: Increase available file watchers
      # https://stackoverflow.com/a/59522493/2560557
      run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install JavaScript Dependencies
      run: yarn install --immutable
    - name: Build for e2e tests
      run: yarn e2e-build
    - name: Install Roc & Roll Dependencies
      run: sudo apt update && sudo apt install ffmpeg
    - name: Install Playwright Dependencies
      # no need for `apt update` since that is already done above
      run: yarn playwright install-deps ${{ matrix.browser }}
    - name: Install Playwright Browser
      run: yarn playwright install ${{ matrix.browser }}
    - name: Run e2e tests
      run: yarn e2e-test --browser=${{ matrix.browser }}
