name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - name: Increase available file watchers
      # https://stackoverflow.com/a/59522493/2560557
      run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
    - name: Checkout
      uses: actions/checkout@master
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install Dependencies
      run: yarn install --immutable
    - name: Tests
      run: yarn test --forceExit
    # - name: Cypress Tests
    #   uses: cypress-io/github-action@v2
    #   with:
    #     install: false
    #     start: yarn run e2e:ci
    #     wait-on: "http://localhost:3003"
    - name: Lint
      run: yarn lint
    - name: Build
      run: yarn build
